name: Data Structure Actions

on: [push]

jobs:
    test:
        name: Data structure tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: 'Install node'
              uses: actions/setup-node@v1
            - name: 'Install dependencies'
              run: npm install
            - name: 'Run Set tests'
              run: npm run test:set
